apiVersion: apps/v1
kind: Deployment
metadata:
  name: filesize-metric-provider
  labels:
    app: filesize-metric-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filesize-metric-provider
  template:
    metadata:
      labels:
        app: filesize-metric-provider
    spec:
      containers:
      - name: filesize-metric-provider
        image: ACR_NAME.azurecr.io/filesize-metric-provider:v1
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        env:
          - name: CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: queue-connect-string
                key: CONNECTION_STRING
          - name: QUEUE_NAME
            value: keda-queue
---

kind: Service
apiVersion: v1
metadata:
  name: filesize-metric-provider-service
  labels:
    app: filesize-metric-provider
spec:
  selector:
    app: filesize-metric-provider
  ports:
    - name: filesize-metric-provider
      protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP